### ISSUE TITLE
index.html 改变路径访问不到

### ISSUE THREAD

**Issue by ytudt** [lzxb/vue-cnode#1]
您好，我运行你的项目时npm run dev 然后访问127.0.0.1:3000是没问题的。
但是我把index.html移动到src目录下，然后访问127.0.0.1:3000/src这样就有问题，请问可以帮忙看看吗？谢谢

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by lzxb** [comment]
看这个文件：https://github.com/lzxb/vue-cnode/blob/master/server.js
将其他路由，全部返回index.html
修改成你移动后的路径

**Comment by ytudt** [comment]
恩，我还有个问题，现在调试时打console 控制台总是报到main.js。有办法在哪个组件中console的就报在哪个组件中吗

**Comment by lzxb** [comment]
你可以试试官方脚手架，因为我是自己学习搭的，所以就没有使用官方的脚手架，不知道官方的脚手架是否支持
