### ISSUE TITLE
关于页面title的问题

### ISSUE THREAD

**Issue by cgkoreyoshi** [lzxb/vue-cnode#10]
如果想实现：每个路由URL都有自己的页面title，该如何做啊？麻烦指导下思路~

**Comment by lzxb** [comment]
页面组件渲染时，手动设置document.title就行了

**Comment by lzxb** [comment]
可以看下这篇文章：https://www.deboy.cn/set-wechat-title-in-vuejs-spa.html

**Comment by cgkoreyoshi** [comment]
@lzxb 多谢
