### ISSUE TITLE
大兄弟，我遇到个问题，能帮我解决一下嘛，谢谢了

### ISSUE THREAD

**Issue by GGStupid** [lzxb/vue-cnode#11]
http://www.vue-js.com/topic/589a7d98a9c1282817afc1a0
这是我在vue论坛问的，但是现在也不知道为什么。如果有时间帮我一下，这问题困扰挺久了

**Comment by lzxb** [comment]
我看看

**Comment by GGStupid** [comment]
恩，谢谢了
