### ISSUE TITLE
实现滚动位置还原时报Unexpected token import的异常

### ISSUE THREAD

**Issue by onlyforhebe** [lzxb/vue-cnode#13]
你好，我想在项目里实现页面后退数据还原，滚动位置还原的效果，结果报错，错误提示为：VM30878:3 Uncaught SyntaxError: Unexpected token import

我的具体做法如下：
1、将lib文件夹复制到项目里；
2、在webpack配置文件里的resolve的alias配置route-data；
3、在main.js里添加import {scrollRecord} from 'route-data'以及Vue.directive('scroll-record', scrollRecord)

在没有引入route-data时没有该错误，如
import Vue from 'vue'
import VueRouter from 'vue-router'
可以正常运行

import Vue from 'vue'
import VueRouter from 'vue-router'
import {scrollRecord} from 'route-data'
报异常VM30878:3 Uncaught SyntaxError: Unexpected token import

**Comment by lzxb** [comment]
语法错误吧

**Comment by onlyforhebe** [comment]
谢谢！初始化vux2项目的问题，如果是直接搭vue的项目没有问题，不知道为什么
