### ISSUE TITLE
content的css样式在哪？

### ISSUE THREAD

**Issue by keepsilenc** [lzxb/vue-cnode#14]
cnodeAPI把那些content加进来渲染好后，发现没有CSS样式，这时候哪里找通用的css样式，因为content是每个人发的内容，所以，自己好像写不了额、

**Comment by lzxb** [comment]
在src/main.js里面有引入css

**Comment by keepsilenc** [comment]
我看你引了许多，这部分主题详情都是靠自己手写的嘛？但是内容都是不一样的哦！！！
我不完全按照你的，我一路写过来，都是自己一个页面写一些css。这样的话我到这步 还可以抄你css的嘛

**Comment by keepsilenc** [comment]
normalize.css我想要的这个文件吗？在哪有的

**Comment by lzxb** [comment]
normalize.css npm安装的，你可以查看我的依赖包

**Comment by keepsilenc** [comment]
前辈，查了一下，normalize是同化多个浏览器的，难不成我要的是这个css和那个github-css....先试下，我只是想要content有样式而已

**Comment by lzxb** [comment]
我都是把css写进对应的组件里面的，你这个要一个个组件进行复制吧

**Comment by keepsilenc** [comment]
1427452572（小号QQ） 能联系下帮我一下嘛，我想截图给你看下

**Comment by lzxb** [comment]
这里也可以上传图片啊

**Comment by keepsilenc** [comment]
![2222](https://cloud.githubusercontent.com/assets/19179908/23163703/860c49de-f86e-11e6-8700-88a2f8fff069.png)

**Comment by lzxb** [comment]
内容的样式都在这里：https://github.com/lzxb/vue-cnode/blob/master/src/pages/topic/vid/index.vue

**Comment by keepsilenc** [comment]
谢谢！
