### ISSUE TITLE
生产模式进不了首页

### ISSUE THREAD

**Issue by HoldSkill** [lzxb/vue-cnode#17]
用了`npm run dist`后，打开index.html无法进入首页。

**Comment by lzxb** [comment]
肯定打开看不了，需要部署到服务器上

**Comment by HoldSkill** [comment]
怎么修改可以在本地打开呢？~

**Comment by lzxb** [comment]
本地搭建一个服务器就行了

**Comment by IceInTheFire** [comment]
webstorm直接运行也无效。
webstorm不是服务器吗？

**Comment by lzxb** [comment]
......你服务器的路径要和你打包出来的程序路径是一样才行，不然js加载失败

**Comment by IceInTheFire** [comment]
要直接写http路径吗？

**Comment by IceInTheFire** [comment]
我想写的是相对路径，不是绝对路径。

**Comment by IceInTheFire** [comment]
我语气不好，我的错。
相比之下，这个demo还是很不错的，毕竟我的vue启蒙demo就是这个demo。

**Comment by HoldSkill** [comment]
谢谢解答~我想实现纯本地打开的……

**Comment by lzxb** [comment]
项目打包配置了服务器的路径，具体看这里
https://github.com/lzxb/vue-cnode/blob/master/configs/base.js
你可以尝试下不配置服务器路径

**Comment by HoldSkill** [comment]
谢谢~修改了`publicPath`,但是路由好像出现了问题，哈哈哈

**Comment by HoldSkill** [comment]
如果您有空，不知道是否可以帮我看一下如何修改成本地直接运行的？万分感激~

**Comment by lzxb** [comment]
。。。。直接打开html运行本身就会有问题

**Comment by HoldSkill** [comment]
酱紫

**Comment by HoldSkill** [comment]
这个不可以实现么？
