### ISSUE TITLE
发帖后跳转到具体的topic点击顶部导航栏回退按钮会回到发帖页面

### ISSUE THREAD

**Issue by UnscientificMisaka** [lzxb/vue-cnode#18]
从前辈的源码中学到了很多，首先向前辈说声谢谢您。
一个小体验问题，发帖后跳转到自己的文章再回退仍是发帖页面晚辈感觉体验不太友好。

**Comment by lzxb** [comment]
那个是`$route.go(-1)`，至于为啥这样，是因为从消息列表点击进去的时候，也需要返回到消息列表。所以就只能这样了咯

**Comment by UnscientificMisaka** [comment]
确实，是我少考虑了消息这块的体验。
