### ISSUE TITLE
你好，我想问下关于页面后退数据还原及滚动条位置还原怎么实现？

### ISSUE THREAD

**Issue by wangdabaoqq** [lzxb/vue-cnode#24]
你好，我想问下关于页面后退数据还原及滚动条位置还原怎么用<keep-alive>结合scrollBehavior,我按照官网的配置方法进行了scrollBehavior的配置,发现在后退是没有办法获取到scrollBehavior的值(值为null)所以想问下您,怎么实现！

**Comment by lzxb** [comment]
`scrollBehavior`没有用过，局限性太小了
