### ISSUE TITLE
v2.1貌似就已经实现了子组件还原

### ISSUE THREAD

**Issue by ldllidonglin** [lzxb/vue-cnode#3]
https://gist.github.com/yyx990803/faebe22e8763f5b17572b35ed96f52fe#conditional-keep-alive

**Comment by lzxb** [comment]
vue本来就支持组件缓存啊，keep-alive组件就可以缓存了。
我的缓存组件是要vue-router才能使用的，具体可以看看这里的代码：
https://github.com/lzxb/vue-cnode/tree/master/src/lib/route-data

**Comment by ldllidonglin** [comment]
vue-router不是也支持组件缓存么？

**Comment by lzxb** [comment]
不支持，组件缓存和页面缓存是两个概念。vue-router可以记录滚动条的坐标，不过是记录的是全局的滚动条位置，可以看这里
https://router.vuejs.org/en/advanced/scroll-behavior.html

vue-cnode是position: absolute;定位布局，要还原的是局部滚动条位置

**Comment by ldllidonglin** [comment]
好吧，我理解的是组件缓存是数据还原，来回切换不会刷新数据，你这里说的是滚动条还原

**Comment by lzxb** [comment]
vue确实是可以缓存组件，但是不同的url都是访问同一个组件，会导致访问其他url的时候，会先渲染上一次页面访问的数据
