### ISSUE TITLE
加注释打包报错

### ISSUE THREAD

**Issue by alasai** [lzxb/vue-cnode#31]
在main.js 单独一行加上注释 // 或者/**/，为什么npm打包就会报错呢，该如何解决

**Comment by lzxb** [comment]
贴出错误原因

**Comment by alasai** [comment]
import components from './components/'
//就是这里了


错误信息

ERROR in ./src/main.js

C:\Users\Administrator\Downloads\vue-cnode-master\vue-cnode-master\src\main.js
  13:1  error  Expected space or tab after '//' in comment  spaced-comment

✖ 1 problem (1 error, 0 warnings)

**Comment by lzxb** [comment]
eslint格式错误

**Comment by alasai** [comment]
请问在哪里配置，可以解决这个问题

**Comment by lzxb** [comment]
是你的代码风格有问题，按照eslint的规范去写就可以了

**Comment by alasai** [comment]
好的，谢谢了
