### ISSUE TITLE
vuet滚动加载返回列表页的默认位置

### ISSUE THREAD

**Issue by alasai** [lzxb/vue-cnode#32]
vuet滚动加载返回列表页，点击其中一条数据查看，再点击返回列表，默认又回到第一条数据位置了，请问如何修改

**Comment by lzxb** [comment]
使用`v-vuet-scroll`指令和vuet模块进行绑定

**Comment by alasai** [comment]
<v-content v-vuet-scroll="{ path: 'bgs-list', name: 'content' }">
这个我已经加了呢

**Comment by lzxb** [comment]
那你列表的数据呢？是怎么管理的

**Comment by lzxb** [comment]
你可以查看一下这个地址的demo：https://github.com/medatc/vuet/tree/dev/examples/scroll-cnode

**Comment by alasai** [comment]
谢谢，解决了，是我加了window.scroll(0, 0)的原因，加这个是因为我用了hash模式 的缘故

**Comment by lzxb** [comment]
能记录滚动条了？

**Comment by alasai** [comment]
不能，因为他必须用history模式，我的是hash模式，请问beforeRouteLeave怎么在路由跳转前获取距离顶部的距离，我想点击返回再返回到制定位置，
beforeRouteLeave(to, from, next){
        next(vm => {
            alert("111")
            alert(vm.$refs.contentref.scrollTop)
        })
    }
这样写法获取不到

**Comment by lzxb** [comment]
应该是在组件销毁之前记录

**Comment by alasai** [comment]
我现在的做法是beforeRouteLeave在这里记录let top=document.documentElement.scrollTop || document.body.scrollTop
        localStorage.setItem("gsktop",top);
然后在 beforeRouteEnter 里写
 if(localStorage.getItem("gsktop")!=null)
            {
                window.scroll(0,localStorage.getItem("gsktop"))
            }
这样确实能实现效果，不过这样的做的话，每个列表页中都得这样做，有点麻烦了

**Comment by lzxb** [comment]
其实你用vuet，不用这么麻烦的

**Comment by lzxb** [comment]
....看楼上demo地址

**Comment by alasai** [comment]
你好，上面的vuetdemo 我看了，
beforeRouteLeave
这里console.log(this.$vuet) 可以获取到vuet，怎么获取到VuetScroll

**Comment by alasai** [comment]
嗯那么请问， this.$vuet.vm 这样的写法，怎么才能获取到距离顶部的scrollTop距离呢
