### ISSUE TITLE
首页异步获取的数据建议缓存

### ISSUE THREAD

**Issue by dcalsky** [lzxb/vue-cnode#4]
每次切换回首页都会获取一次最新的帖子 虽然能及时获取新帖子 但是增加了等待时间 降低了体验
建议把数据保存在本地 然后用主动刷新替代自动的

**Comment by lzxb** [comment]
其实它的原理是这样子的，如果你是前进到首页的话，会重新初始化数据，后退到首页，则是直接从缓存中还原上次的状态。


点击首页-->点击发表-->点击首页  这个过程。都是往历史里面添加一条记录，所以这个过程是重新初始化数据

点击首页-->点击发表-->后退  这个过程，是后退一步，所以不会重新初始化数据，而是直接从缓存中还原状态

**Comment by lzxb** [comment]
这个目前实现得比较简单，仅仅能缓存一级数据和一级组件。可能最近会开发这个一个专门针对vue-router的缓存模块。
