### ISSUE TITLE
缓存的数据如果有改变，怎么更新呢？

### ISSUE THREAD

**Issue by docikaci** [lzxb/vue-cnode#6]
列表页和详情页都有缓存数据，但是缓存的数据变了呢，比如说在列表点赞收藏后，个数就变了，然后进入到详情，在返回列表，怎么更新列表数据？

这个demo，怎么登陆呢 token是啥？（想测下评论后数据变化，怎么处理的）

顺便说下，楼主有换工作打算吗，tencent欢迎你

**Comment by lzxb** [comment]
token在https://cnodejs.org/注册后，在设置的di'bu底部有
目前的缓存实现得比较简单，首次进入组件时组件和url、历史状态关联的状态还是默认的
首次访问-->页面状态是默认的-->拉取服务器数据-->更新状态-->页面离开时存储状态
第二次访问-->取上一次访问此页面的状态-->拉取服务器数据-->更新状态

其实vue-router的缓存可以做得更好的，只是因为时间有限，就撸了一个比较简单的，没有能够和vue的响应式系统关联到一起

**Comment by lzxb** [comment]
腾讯？深圳吗？

**Comment by docikaci** [comment]
北京的

**Comment by lzxb** [comment]
666
