### ISSUE TITLE
import mint-ui 报错

### ISSUE THREAD

**Issue by Michael-5h** [lzxb/vue-cnode#7]
项目引入mint-ui提示Module build failed: Error: Couldn't find preset "es2015-rollup" relative to directory

**Comment by lzxb** [comment]
这个应该是mint-ui引入的什么模块导致的，vue-cnode没有使用这个模块

**Comment by Michael-5h** [comment]
我尝试过其他项目import mint-ui不会报错的 使用方法都是参考官方文档的

**Comment by lzxb** [comment]
你去node_modules目录下找找mint-ui有没有.babelrc这个文件
