### ISSUE TITLE
回复的小尾巴似乎有点问题

### ISSUE THREAD

**Issue by TakWolf** [lzxb/vue-cnode#8]
问题帖子：
https://cnodejs.org/topic/586e392abcf66127778bd2eb

![image](https://cloud.githubusercontent.com/assets/6064962/21833168/38fdd246-d7eb-11e6-82e7-f4b361589557.png)

![image](https://cloud.githubusercontent.com/assets/6064962/21833236/aaa80ee8-d7eb-11e6-9811-2a81e55dce6c.png)

```
"content": "<div class=\"markdown-text\"><p><a href=\"/user/dianjie\">@dianjie</a> 你666</p>\n<p>&lt;br&gt;来自&lt;a href=“<a href=\"https://lzxb.github.io/vue-cnode/\">https://lzxb.github.io/vue-cnode/</a>” target=&quot;_blank&quot;&gt;vue-cnode手机版&lt;/a&gt;</p>\n</div>"
```

**Comment by lzxb** [comment]
好的，感谢回复。我刚才也看到了，等下抽时间修复一下

**Comment by lzxb** [comment]
当然了，你也可以pull代码过滤

**Comment by lzxb** [comment]
这个bug已经被修复了，谢谢。
